### ISSUE TITLE
Dependency conflict gevent 1.3.4 vs. gevent 1.4.0

### ISSUE THREAD

**Issue by dsmits** [IKNL/vantage6-master#1]
It seems like all libraries that are installed in the [Dockerfile](https://github.com/IKNL/vantage6-master/blob/master/Dockerfile) use `gevent 1.4.0`. However, the dockerfile itself installs `gevent 1.3.4`.
This gives dependency conflicts when building and running the vantage6 node.

It looks like installing `gevent 1.3.4` in the dockerfile was a temporary solution for something. Is it possible that this temporary solution can be removed?

**Comment by bartvanb** [comment]
This has been resolved a while back (https://github.com/IKNL/vantage6-master/commit/335ee178c0d685b1fe5c8945f65fe89da317bdf6) when we upgraded the SocketIO dependencies
